altra-128c-256gb-scarthgap-2024-06: just very small teaser
* unfortunately need to fix chromium:
     ../../base/allocator/partition_allocator/src/partition_alloc/reservation_offset_table.h:107:8: error: fields must have a constant size: 'variable length array in structure' extension will never be supported

  and qtwebengine:
     ERROR at //skia/BUILD.gn:825:5: Assertion failed.
     assert(false, "Need to port cpu specific stuff from skia_library_opts.gyp")
     ^-----

  to build on aarch64 host

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>