1-init.sh: use a bit older meta-rust revision to build firefox
* rust-1.38.0 and newer causes firefox build to fail with:
 3:18.49    Compiling kvstore v0.1.0 (poky/build/tmp/work/core2-64-poky-linux/firefox/68.0esr-r0/firefox-68.0/toolkit/components/kvstore)
 3:18.53 error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
 3:18.53    --> /usr/src/debug/firefox/68.0esr-r0/firefox-68.0/third_party/rust/cssparser/src/parser.rs:584:17
 3:18.53     |
 3:18.53 559 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
 3:18.53     |                                                   - let's call the lifetime of this reference `'1`
 3:18.53 ...
 3:18.53 572 |             Some(ref cached_token)
 3:18.53     |                  ---------------- borrow of `self.input.cached_token` occurs here
 3:18.53 ...
 3:18.53 584 |                 self.input.cached_token = Some(CachedToken {
 3:18.53     |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
 3:18.53 ...
 3:18.53 596 |         Ok(token)
 3:18.53     |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`
 3:18.80 error: aborting due to previous error
 3:18.80 For more information about this error, try `rustc --explain E0506`.
 3:18.83 error: could not compile `cssparser`.
 3:18.83 warning: build failed, waiting for other jobs to finish...

* use older meta-rust with rust-1.37.0 to quickly work around this issues
  as we're only interested in the build time

Signed-off-by: Martin Jansa <martin.jansa@lge.com>